name: dart_dot_reporter_pong
description: A starting point for Dart libraries or applications.
version: 1.0.3
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

executables:
  dart_dot_reporter_pong: dart_dot_reporter_pong

# Add regular dependencies here.
#dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  mocktail: ^1.0.4
